version: '3.8'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    #container_name:  Mywordpress
    restart: always
    volumes:
      - D:/DevOps/Docker-Exrs/My-DockComposer/wordpress:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: Chgitem12
      WORDPRESS_DB_NAME: mywordpress
    networks:
        - my-net
     #volumes:
      #  db:
  db:
   image: mysql:latest
   container_name: MyDBContainer
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=Chgitem12
     - MYSQL_DATABASE=MyHomeworkDatabase
   volumes:
     - D:/DevOps/Docker-Exrs/My-DockComposer/db:/var/lib/mysql 
   networks:
        - my-net  
  nginx:
     depends_on:
       - wordpress
     restart: always
     container_name: My-nginx
     build:
       context: .
       dockerfile: DockerFile-nginx
     ports:
       - "80:80"   
     networks:
        - my-net            
networks:
   my-net:
     driver: bridge 

